### ISSUE TITLE
Node Crashes When Getting Master Playlist

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#124]
Steps to repro:
1. Start node1 on 1935, 8935
2. Broadcast to node1, watch from another node
3. Start node2 on 1936, 8936 (with the same datadir, so it's using the same nodeID as the node1)
4. Broadcast to node2
5. Watch stream 2 from another node

Node 1 crashes

```
I0913 01:03:50.231119    9204 lpms.go:100] Segment RTMP Req: rtmp://localhost:1936/stream/122024506e16a51b9853ae5a019d7d99549414e7c053116f6de533cac987ace384206b35e66106f2866055cc50fa5b71365cd5d51cf3d6ea7489e84365d26c3646de
I0913 01:03:50.232097    9204 video_segmenter.go:93] Ffmpeg path:
I0913 01:03:50.262789    9204 player.go:53] LPMS got RTMP request @ rtmp://localhost:1936/stream/122024506e16a51b9853ae5a019d7d99549414e7c053116f6de533cac987ace384206b35e66106f2866055cc50fa5b71365cd5d51cf3d6ea7489e84365d26c3646de
I0913 01:04:13.746050    9204 basic_network.go:288] 122024506e16a51b9853ae5a019d7d99549414e7c053116f6de533cac987ace38420 Received a message 5 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0913 01:04:13.774989    9204 basic_network.go:288] 122024506e16a51b9853ae5a019d7d99549414e7c053116f6de533cac987ace38420 Received a message 2 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0913 01:05:54.881826    9204 mediaserver.go:174] Error in segmenter: FFMpegSegmenterError, broadcasting finish message
I0913 01:06:16.661627    9204 basic_network.go:288] 122024506e16a51b9853ae5a019d7d99549414e7c053116f6de533cac987ace38420 Received a message 5 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x442a3b6]

goroutine 205 [running]:
github.com/livepeer/go-livepeer/vendor/github.com/ericxtang/m3u8.(*MasterPlaylist).Encode(0x0, 0xc4201ac8c0)
	/Users/ericxtang/go/src/github.com/livepeer/go-livepeer/vendor/github.com/ericxtang/m3u8/writer.go:77 +0x46
github.com/livepeer/go-livepeer/vendor/github.com/ericxtang/m3u8.(*MasterPlaylist).String(0x0, 0x22, 0xc4201e6a80)
	/Users/ericxtang/go/src/github.com/livepeer/go-livepeer/vendor/github.com/ericxtang/m3u8/writer.go:251 +0x2f
github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet.handleGetMasterPlaylistReq(0xc42044b740, 0xc4201caaf0, 0xc4200950e0, 0x84, 0x3, 0x3)
	/Users/ericxtang/go/src/github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet/basic_network.go:532 +0x93
github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet.streamHandler(0xc42044b740, 0xc4201caaf0, 0x0, 0x0)
	/Users/ericxtang/go/src/github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet/basic_network.go:330 +0xb9b
github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet.(*BasicVideoNetwork).SetupProtocol.func1(0x4d0df80, 0xc4201980e0)
	/Users/ericxtang/go/src/github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet/basic_network.go:269 +0xef
github.com/livepeer/go-livepeer/vendor/gx/ipfs/QmXZyBQMkqSYigxhJResC6fLWDGFhbphK67eZoqMDUvBmK/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1(0xc4201980a0, 0x15, 0x51c2968, 0xc4201980e0, 0x21e72, 0xc4201d62a0)
	/Users/ericxtang/go/src/github.com/livepeer/go-livepeer/vendor/gx/ipfs/QmXZyBQMkqSYigxhJResC6fLWDGFhbphK67eZoqMDUvBmK/go-libp2p/p2p/host/basic/basic_host.go:320 +0x9d
created by github.com/livepeer/go-livepeer/vendor/gx/ipfs/QmXZyBQMkqSYigxhJResC6fLWDGFhbphK67eZoqMDUvBmK/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
	/Users/ericxtang/go/src/github.com/livepeer/go-livepeer/vendor/gx/ipfs/QmXZyBQMkqSYigxhJResC6fLWDGFhbphK67eZoqMDUvBmK/go-libp2p/p2p/host/basic/basic_host.go:284 +0x839
exit status 2
```

**Comment by ericxtang** [comment]
fixed in https://github.com/livepeer/go-livepeer-basicnet/pull/12
