### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by criticaltv** [livepeer/go-livepeer#1304]
**Describe the bug**

When running livepeer `0.5.3` on rinkeby, I am consistently getting a `panic: runtime error` when streaming into the broadcaster.

**To Reproduce**

I am able to reproduce by running the following processes on the same server (Ubuntu):

For `orchestrator` process:
```
./livepeer-linux-amd64/livepeer -orchestrator -cliAddr 127.0.0.1:7936 -httpAddr 127.0.0.1:8936 -serviceAddr 127.0.0.1:8936 -pricePerUnit 20000000 -pixelsPerUnit 1 -ticketEV 1000000000000000 -orchSecret secret -v 99 -network rinkeby
```

For `transcoder` process
```
./livepeer-linux-amd64/livepeer -transcoder -orchAddr 127.0.0.1:8936 -cliAddr 127.0.0.1:7937 -httpAddr 127.0.0.1:8937 -orchSecret secret -maxSessions 1 -v 99 -network rinkeby
```

For `broadcaster` process
```
./livepeer-linux-amd64/livepeer -broadcaster -cliAddr 127.0.0.1:7935 -rtmpAddr 127.0.0.1:1935 -httpAddr 0.0.0.0:8935 -orchAddr 127.0.0.1:8936 -transcodingOptions P144p30fps16x9 -depositMultiplier 1 -maxPricePerUnit 25000000 -pixelsPerUnit 1 -maxTicketEV 10000000000000000 -v 99 -network rinkeby
```

And then streaming into the `broadcaster` in a `publisher` process:
```
ffmpeg -re -f lavfi -i testsrc=size=256x144:rate=30,format=yuv420p -f lavfi -i sine -threads 1 -c:v libx264 -b:v 1000k -preset ultrafast -x264-params keyint=30 -strict -2 -c:a aac -f flv rtmp://127.0.0.1:1935/hello_world
```

Resulting behaviour:

```
ubuntu@ip-172-31-43-225:~$ ./livepeer-linux-amd64/livepeer -broadcaster -cliAddr 127.0.0.1:7935 -rtmpAddr 127.0.0.1:1935 -httpAddr 0.0.0.0:8935 -orchAddr 127.0.0.1:8936 -transcodingOptions P144p30fps16x9 -depositMultiplier 1 -maxPricePerUnit 25000000 -pixelsPerUnit 1 -maxTicketEV 10000000000000000 -v 99 -network rinkeby
I0114 13:02:52.892025    2699 livepeer.go:203] ***Livepeer is running on the rinkeby network: 0xA268AEa9D048F8d3A592dD7f1821297972D4C8Ea***
I0114 13:02:52.893067    2699 db.go:316] Initialized DB node
I0114 13:02:53.416434    2699 accountmanager.go:61] Found existing ETH account
I0114 13:02:53.416465    2699 accountmanager.go:188] Defaulting to first ETH account in keystore 0xDAC817294c0c87ca4fA1895eF4b972EAde99f2fd
I0114 13:02:53.416552    2699 accountmanager.go:70] Using Ethereum account: 0xDAC817294c0c87ca4fA1895eF4b972EAde99f2fd
I0114 13:02:54.398389    2699 accountmanager.go:93] Please enter the passphrase to unlock Ethereum account 0xDAC817294c0c87ca4fA1895eF4b972EAde99f2fd
Passphrase:
I0114 13:02:59.857319    2699 accountmanager.go:104] Unlocked ETH account: 0xDAC817294c0c87ca4fA1895eF4b972EAde99f2fd
I0114 13:02:59.857623    2699 client.go:215] Controller: 0xA268AEa9D048F8d3A592dD7f1821297972D4C8Ea
I0114 13:02:59.964321    2699 client.go:236] LivepeerToken: 0x23b814a57D53b1a7A860194F53401D0D639abED7
I0114 13:03:00.087567    2699 client.go:257] ServiceRegistry: 0xa7AFBB45eb8C27a26379F9C550B3b9be7f09c3eA
I0114 13:03:00.191952    2699 client.go:278] BondingManager: 0xe75a5DccfFe8939F7f16CC7f63EB252bB542FE95
I0114 13:03:00.297939    2699 client.go:299] TicketBroker: 0x40897Ff6e44Ca2e145A691701897844669Bf7cee
I0114 13:03:00.406250    2699 client.go:320] RoundsManager: 0x572d1591bD41f50130FD0212058eAe34F1B17290
I0114 13:03:00.512472    2699 client.go:341] Minter: 0xe5056d1fE48F562dd8AcB1BBFFa147223d448C1B
I0114 13:03:00.613638    2699 client.go:362] LivepeerTokenFaucet: 0x6b752dA302C80795ACc9347AF8f472D3473b19f2
I0114 13:03:01.052741    2699 livepeer.go:770] ***Livepeer Running in Broadcaster Mode***
I0114 13:03:01.052788    2699 livepeer.go:771] Video Ingest Endpoint - rtmp://127.0.0.1:1935
I0114 13:03:01.052899    2699 webserver.go:68] CLI server listening on 127.0.0.1:7935
I0114 13:03:01.053030    2699 mediaserver.go:139] Transcode Job Type: [{P144p30fps16x9 400k 30 256x144 16:9}]
I0114 13:03:01.053182    2699 mediaserver.go:161] HTTP Server listening on http://0.0.0.0:8935
I0114 13:03:01.053236    2699 lpms.go:92] LPMS Server listening on rtmp://127.0.0.1:1935
I0114 13:03:08.398021    2699 listener.go:36] RTMP server got upstream: rtmp://127.0.0.1:1935/hello_world
I0114 13:03:08.823213    2699 broadcast.go:117] Starting session refresh
I0114 13:03:08.823280    2699 rpc.go:223] Connecting RPC to https://127.0.0.1:8936
I0114 13:03:09.036412    2699 discovery.go:105] Done fetching orch info for orchestrators, numResponses fetched: 1
I0114 13:03:09.036690    2699 broadcast.go:161] Ending session refresh
I0114 13:03:09.036716    2699 mediaserver.go:350]

Video Created With ManifestID: hello_world

I0114 13:03:09.036754    2699 lpms.go:149] Segment RTMP Req: rtmp://127.0.0.1:1935/stream/hello_world/fe478f1cbf1b
I0114 13:03:09.166110    2699 player.go:63] LPMS got RTMP request @ rtmp://127.0.0.1:1935/stream/hello_world/fe478f1cbf1b
I0114 13:03:13.545414    2699 broadcast.go:256] Processing segment nonce=2698611182413602751 manifestID=hello_world seqNo=0 dur=1.98
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xf32e2b]

goroutine 92 [running]:
github.com/livepeer/go-livepeer/server.(*BroadcastSessionsManager).selectSession(0xc0007dcd40, 0x0)
        /build/server/broadcast.go:78 +0xcb
github.com/livepeer/go-livepeer/server.transcodeSegment(0xc00018f7a0, 0xc000755540, 0xc000578c30, 0xb, 0x0, 0x3fffae147ae147ae, 0x0)
        /build/server/broadcast.go:304 +0x68
github.com/livepeer/go-livepeer/server.processSegment(0xc00018f7a0, 0xc000755540, 0x0, 0xc000827b60)
        /build/server/broadcast.go:292 +0x488
created by github.com/livepeer/go-livepeer/server.gotRTMPStreamHandler.func1.1.1
        /build/server/mediaserver.go:330 +0x62
ubuntu@ip-172-31-43-225:~$ 
```

**Expected behaviour**

I expect that it should start to transcode video content via the `orchestrator`.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1
```
ubuntu@ip-172-31-43-225:~$ ./livepeer-linux-amd64/livepeer -version
Livepeer Node Version: 0.5.3
Golang runtime version: gc go1.13.4
Architecture: amd64
Operating system: linux
```

**Additional context**

When running the same commands offchain, i.e. without the `-network rinkeby`, everything runs fine.

**Comment by yondonfu** [comment]
Re-posting another report from Discord below:

> I'm encountering the following error when trying to broadcast with v0.5.3 on Rinkeby: [h264 @ 0x8009e00] co located POCs unavailable. This occur immediately after trying to stream content from OBS. Shortly after that, the broadcasting node crashes with a segmentation error:

> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x4a9a19b]

> Any idea what might cause this?

The broadcaster was started with the following command:

```
./livepeer -network rinkeby -broadcaster -datadir ./livepeer-dir -orchAddr <IP>:8935 -v 6
```

The orchestrator was started with the following command:

```
./livepeer -network rinkeby -orchestrator -transcoder -pricePerUnit 1 -datadir ./livepeer-dir -serviceAddr <IP>:8935 -v 99
```

**Comment by yondonfu** [comment]
I am going to open a PR with a fix soon, but in the meantime a workaround for this issue is to first run the broadcaster *without* the `-orchAddr` flag and wait until you see the following logs:

```
CLI server listening on <IP>:<PORT>
HTTP server listening on http://<IP>:<PORT>
LPMS server listening on rtmp://<IP>:<PORT>
```

Then restart the broadcaster *with* the `-orchAddr` flag. You only have to run the broadcaster without the `-orchAddr` flag once. For anyone interested in the cause of the bug read on below.

This bug is caused by the following:

- The broadcaster has a clean DB
- The broadcaster connects to Rinkeby and specifies a specific active orchestrator using the `-orchAddr` flag
- During selection, the broadcaster tries to read the stake for the orchestrator from its DB, but fails to do so because the DB was never populated
- The broadcaster skips and removes the orchestrator from its session list
- The selector [returns nil](https://github.com/livepeer/go-livepeer/blob/master/server/selection.go#L207) because the session list is empty
- There is no nil check for the session [here](https://github.com/livepeer/go-livepeer/blob/master/server/broadcast.go#L78)

**Comment by criticaltv** [comment]
This does indeed fix this interesting edge case. Is there a bug bounty for this? @ericxtang ?
