### ISSUE TITLE
SIGSEGV on booting orchestrator without -pricePerUnit

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#1361]
Reproduced this with slightly different errors on both v0.5.3 and v0.5.4.

Steps I went through:

1. Created a new wallet on Darwin, with `livepeer -broadcaster -network mainnet`. Entered password `elisecret`.
1. Moved that data directory so it could be bind-mounted by Docker `mv ~/.lpData ~/.lpData-o`
1. Ran Docker with a bind-mounted directory as shown in the following command.

Running with a hardcoded `-pricePerUnit 1` fixes the issue in both cases.

This is v0.5.3:
```
docker run 
  --rm 
  -it 
  -p 8936:8936
  -p 7936:7936
  -v /Users/iameli/.lpData-o:/root/.lpData
   livepeer/go-livepeer:mainnet 
  -network mainnet
  -orchestrator
  -orchSecret elisecret
  -serviceAddr 10.9.168.95:8936
  -ethPassword elisecret

I0205 23:23:58.255607       1 livepeer.go:203] ***Livepeer is running on the mainnet network: 0xf96d54e490317c557a967abfa5d6e33006be69b3***
I0205 23:23:58.941439       1 accountmanager.go:70] Using Ethereum account: 0x3A958dc8f89b1643cb78218709eC0D2f1950afb9
I0205 23:24:00.247371       1 accountmanager.go:104] Unlocked ETH account: 0x3A958dc8f89b1643cb78218709eC0D2f1950afb9
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf64fcc]

goroutine 49 [running]:
github.com/livepeer/go-livepeer/eth/watchers.(*OrchestratorWatcher).Watch(0xc0004ec410)
	/build/eth/watchers/orchestratorwatcher.go:47 +0x7c
created by main.main
	/build/cmd/livepeer/livepeer.go:441 +0x2e2c
```

Different error on v0.5.3:

```
./livepeer -network mainnet -orchestrator -orchSecret elisecret -serviceAddr 10.9.168.95:8936 -ethPassword elisecret
I0205 23:32:29.945967     527 livepeer.go:203] ***Livepeer is running on the mainnet network: 0xf96d54e490317c557a967abfa5d6e33006be69b3***
I0205 23:32:30.612968     527 accountmanager.go:70] Using Ethereum account: 0x3A958dc8f89b1643cb78218709eC0D2f1950afb9
I0205 23:32:31.331973     527 accountmanager.go:104] Unlocked ETH account: 0x3A958dc8f89b1643cb78218709eC0D2f1950afb9
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf62e4c]

goroutine 32 [running]:
github.com/livepeer/go-livepeer/eth/watchers.(*OrchestratorWatcher).Watch(0xc0000c7a40)
	/build/eth/watchers/orchestratorwatcher.go:47 +0x7c
created by main.main
	/build/cmd/livepeer/livepeer.go:441 +0x2e2c
panic: Price per unit of pixels must be greater than 0, provided 0 instead


goroutine 1 [running]:
main.main()
	/build/cmd/livepeer/livepeer.go:464 +0x7a21
```

**Comment by kyriediculous** [comment]
In the first case, the broadcaster uses `-maxPricePerPixel` and `-pixelsPerUnit` it doesn't use the `-pricePerPixel` flag.

I suspect the `OrchestratorWatcher.Watch()` error is unrelated to the flag but I don't see this occuring any longer either.

Are you still encountering this in the latest release (>=0.5.5) ?  Chances are that this coincidentally got fixed in one of the recent releases.

I just tried on rinkeby and got a proper panic omitting the `-pricePerUnit` flag and didn't observe a secondary `SIGSEGV` violation:

```
nico@Nicos-MacBook-Pro go-livepeer (nv/priceinfo-race) $ ./livepeer -network rinkeby -orchestrator -transcoder -ethUrl https://rinkeby.infura.io/v3/09642b98164d43eb890939eb9a7ec500
I0420 02:57:44.413021   57774 livepeer.go:204] ***Livepeer is running on the rinkeby network: 0xA268AEa9D048F8d3A592dD7f1821297972D4C8Ea***
I0420 02:57:45.195970   57774 accountmanager.go:70] Using Ethereum account: 0x13d3C3bdDD3531d11F92884bC49cb98255D51370
I0420 02:57:45.904333   57774 accountmanager.go:93] Please enter the passphrase to unlock Ethereum account 0x13d3C3bdDD3531d11F92884bC49cb98255D51370
Passphrase:
I0420 02:57:52.746737   57774 accountmanager.go:104] Unlocked ETH account: 0x13d3C3bdDD3531d11F92884bC49cb98255D51370
panic: Price per unit of pixels must be greater than 0, provided 0 instead


goroutine 1 [running]:
main.main()
	/Users/nico/Desktop/livepeer/go-livepeer/cmd/livepeer/livepeer.go:471 +0x7de2
``` 

Closing for now, feel free to re-open if this still occurs.
