### ISSUE TITLE
panic: runtime error in version 0.5.5

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1420]
**Describe the bug**

Livepeer binaries running in `-orchestrator` mode failing with runtime error under specific use-case.

**To Reproduce**

1. Run a B with:
```
./livepeer-linux-amd64/livepeer -network rinkeby -broadcaster -cliAddr 127.0.0.1:7935 -rtmpAddr 127.0.0.1:1935 -httpAddr 0.0.0.0:8935 -orchAddr 127.0.0.1:8936 -transcodingOptions P144p30fps16x9 -depositMultiplier 1 -maxPricePerUnit 5000000000 -pixelsPerUnit 1 -maxTicketEV 1000000000000000000 -v 99
```
2. Wait for the B to report `LPMS Server listening on rtmp://127.0.0.1:1935`

3. Publish content into the B with the command below:
```
ffmpeg -re -f lavfi -i testsrc=size=256x144:rate=30,format=yuv420p -f lavfi -i sine -threads 1 -c:v libx264 -b:v 1000k -preset ultrafast -x264-params keyint=30 -strict -2 -c:a aac -f flv rtmp://127.0.0.1:1935/hello_world
```
4. Run an O with the following command (note, no process is running as `-transcoder`)
```
./livepeer-linux-amd64/livepeer -network rinkeby -orchestrator -cliAddr 127.0.0.1:7936 -httpAddr 127.0.0.1:8936 -serviceAddr 127.0.0.1:8936 -pricePerUnit 2000000000 -pixelsPerUnit 1 -ticketEV 1000000000000000 -orchSecret secret -v 99
```
5. See the following log from the O:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5bd4f9]
```
(Full log output from process below)

**Expected behavior**

In this case, I expect that the O will publish no available sessions to the B, and wait until a T registers to it.

This case models when a O goes offline while a B is already processing content. When the O comes back online, there would be a time when the B is sending to the O, before any Ts have registered.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
```
ubuntu@ip-172-31-43-225:~$ ./livepeer-linux-amd64/livepeer -version
Livepeer Node Version: 0.5.5
Golang runtime version: gc go1.13.4
Architecture: amd64
Operating system: linux
```

**Log**
From `-orchestrator` process which crashed:
```
ubuntu@ip-172-31-43-225:~$ ./livepeer-linux-amd64/livepeer -network rinkeby -orchestrator -cliAddr 127.0.0.1:7936 -httpAddr 127.0.0.1:8936 -serviceAddr 127.0.0.1:8936 -pricePerUnit 2000000000 -pixelsPerUnit 1 -ticketEV 1000000000000000 -orchSecret secret -v 99
I0313 11:11:40.660593    2660 livepeer.go:204] ***Livepeer is running on the rinkeby network: 0xA268AEa9D048F8d3A592dD7f1821297972D4C8Ea***
I0313 11:11:40.661783    2660 db.go:316] Initialized DB node
I0313 11:11:41.177397    2660 accountmanager.go:61] Found existing ETH account
I0313 11:11:41.177425    2660 accountmanager.go:188] Defaulting to first ETH account in keystore 0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
I0313 11:11:41.177442    2660 accountmanager.go:70] Using Ethereum account: 0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
I0313 11:11:42.164207    2660 accountmanager.go:93] Please enter the passphrase to unlock Ethereum account 0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Passphrase: 
I0313 11:11:46.207982    2660 accountmanager.go:104] Unlocked ETH account: 0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
I0313 11:11:46.208287    2660 client.go:215] Controller: 0xA268AEa9D048F8d3A592dD7f1821297972D4C8Ea
I0313 11:11:46.324241    2660 client.go:236] LivepeerToken: 0x23b814a57D53b1a7A860194F53401D0D639abED7
I0313 11:11:46.427484    2660 client.go:257] ServiceRegistry: 0xa7AFBB45eb8C27a26379F9C550B3b9be7f09c3eA
I0313 11:11:46.530619    2660 client.go:278] BondingManager: 0xe75a5DccfFe8939F7f16CC7f63EB252bB542FE95
I0313 11:11:46.656612    2660 client.go:299] TicketBroker: 0x40897Ff6e44Ca2e145A691701897844669Bf7cee
I0313 11:11:46.761289    2660 client.go:320] RoundsManager: 0x572d1591bD41f50130FD0212058eAe34F1B17290
I0313 11:11:46.868399    2660 client.go:341] Minter: 0xe5056d1fE48F562dd8AcB1BBFFa147223d448C1B
I0313 11:11:46.977089    2660 client.go:362] LivepeerTokenFaucet: 0x6b752dA302C80795ACc9347AF8f472D3473b19f2
I0313 11:11:47.087770    2660 livepeer.go:469] Price: 2000000000 wei for 1 pixels
 
I0313 11:11:47.831603    2660 livepeer.go:898] Orchestrator 0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX is active
I0313 11:11:47.934238    2660 gaspricemonitor.go:134] Cached gas price: 1000000000
I0313 11:11:48.050917    2660 block_watcher.go:318] Backfilling block events (this can take a while)...
I0313 11:11:48.050945    2660 block_watcher.go:319] Start block: 6130376		 End block: 6130375		Blocks elapsed: -1
I0313 11:11:48.057024    2660 block_watcher.go:537] fetching block logs from=6130376 to=6130375
I0313 11:11:48.157951    2660 livepeer.go:777] ***Livepeer Running in Orchestrator Mode***
I0313 11:11:48.158044    2660 mediaserver.go:141] Transcode Job Type: [{P240p30fps16x9 600k 30 426x240 16:9} {P360p30fps16x9 1200k 30 640x360 16:9}]
I0313 11:11:48.158168    2660 cert.go:83] Private key and cert not found. Generating
I0313 11:11:48.158170    2660 webserver.go:70] CLI server listening on 127.0.0.1:7936
I0313 11:11:48.158438    2660 cert.go:22] Generating cert for 127.0.0.1
I0313 11:11:48.158745    2660 rpc.go:155] Listening for RPC on 127.0.0.1:8936
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5bd4f9]

goroutine 105 [running]:
math/big.(*Int).Add(0xc000299a40, 0x0, 0xc00037f360, 0xc0fdf299de)
	/usr/lib/go-1.13/src/math/big/int.go:117 +0x29
github.com/livepeer/go-livepeer/pm.(*recipient).TicketParams(0xc00072a2d0, 0xca870c4c2917c8da, 0xea72b9f45e89a14f, 0xc0fdf299de, 0xc0007a8880, 0x0, 0x0, 0x1)
	/build/pm/recipient.go:221 +0x196
github.com/livepeer/go-livepeer/core.(*orchestrator).TicketParams(0xc0001f0fc0, 0xca870c4c2917c8da, 0xea72b9f45e89a14f, 0xc0fdf299de, 0xc0006a2188, 0x0, 0x0)
	/build/core/orchestrator.go:238 +0xe6
github.com/livepeer/go-livepeer/server.orchestratorInfo(0x1f6dbe0, 0xc0001f0fc0, 0xca870c4c2917c8da, 0xea72b9f45e89a14f, 0xfdf299de, 0xc00068f8c0, 0x16, 0x50, 0x0, 0x0)
	/build/server/rpc.go:256 +0x52
github.com/livepeer/go-livepeer/server.getOrchestrator(0x1f6dbe0, 0xc0001f0fc0, 0xc000128f50, 0x1b6a9e0, 0xc000771800, 0x1f49080)
	/build/server/rpc.go:252 +0x21c
github.com/livepeer/go-livepeer/server.(*lphttp).GetOrchestrator(0xc00028dde0, 0x1f5b200, 0xc000277b30, 0xc000128f50, 0xc00028dde0, 0xc000277b30, 0xc000063a80)
	/build/server/rpc.go:128 +0x41
github.com/livepeer/go-livepeer/net._Orchestrator_GetOrchestrator_Handler(0x1b6a9e0, 0xc00028dde0, 0x1f5b200, 0xc000277b30, 0xc000771860, 0x0, 0x1f5b200, 0xc000277b30, 0xc000780060, 0x59)
	/build/net/lp_rpc.pb.go:1341 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00073eb00, 0x1f67b20, 0xc0001e1320, 0xc0000f7d00, 0xc0001f10e0, 0x2b65080, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:995 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc00073eb00, 0x1f67b20, 0xc0001e1320, 0xc0000f7d00, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1275 +0xd97
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004934e0, 0xc00073eb00, 0x1f67b20, 0xc0001e1320, 0xc0000f7d00)
	/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:710 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:708 +0xa1
```

**Comment by kyriediculous** [comment]
Here's the cause 

I0313 11:11:48.050945    2660 block_watcher.go:319] Start block: 6130376		 End block: 6130375		Blocks elapsed: -1

There are no blocks being backfilled so `lastBlock` [ here ](https://github.com/livepeer/go-livepeer/blob/ce819a15a616277a7081b5cb91339c4121a22538/pm/recipient.go#L220 ) is going to be nil. Reasons this can happen:
- Infura node we're connecting to hasn't seen the latest block we have previously discovered yet
- We are restarting the node within the same block height still

I initially had an RPC call populate this field but removed it because it _should_ be populated through backfilling but I didn't take into account the two cases mentioned above. 

Will submit a fix soon.

**Comment by criticaltv** [comment]
Thanks @kyriediculous - I had also noticed this but just assumed that someone had confused the start block and the end block in the logging output.

It happens every time I restart this process...
