### ISSUE TITLE
Segfault while running livepeer node

### ISSUE THREAD

**Issue by 0x1F602** [livepeer/go-livepeer#160]
```I1012 06:00:24.933530   31145 mediaserver.go:75] Transcode Job Price: 1, Transcode Job Type: {P360p30fps16x9 1000k 30 16:9 640:360}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x829fc6]

goroutine 1610 [running]:
github.com/livepeer/go-livepeer/vendor/github.com/ericxtang/m3u8.(*MasterPlaylist).Encode(0x0, 0xc420197b00)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/github.com/ericxtang/m3u8/writer.go:77 +0x46
github.com/livepeer/go-livepeer/vendor/github.com/ericxtang/m3u8.(*MasterPlaylist).String(0x0, 0x22, 0xc4201b0180)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/github.com/ericxtang/m3u8/writer.go:251 +0x2f
github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet.handleGetMasterPlaylistReq(0xc420190380, 0xc420445950, 0xc420086a00, 0x92, 0x3, 0x3)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet/basic_network.go:532 +0x93
github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet.streamHandler(0xc420190380, 0xc420445950, 0xc420169740, 0xc42047a158)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet/basic_network.go:330 +0xb9b
github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet.(*BasicVideoNetwork).SetupProtocol.func1(0x132b140, 0xc4200bb1a0)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet/basic_network.go:269 +0xef
github.com/livepeer/go-livepeer/vendor/gx/ipfs/QmXZyBQMkqSYigxhJResC6fLWDGFhbphK67eZoqMDUvBmK/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1(0xc4200bb160, 0x15, 0x7f693bb75378, 0xc4200bb1a0, 0x7e69, 0xc420192260)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/gx/ipfs/QmXZyBQMkqSYigxhJResC6fLWDGFhbphK67eZoqMDUvBmK/go-libp2p/p2p/host/basic/basic_host.go:320 +0x9d
created by github.com/livepeer/go-livepeer/vendor/gx/ipfs/QmXZyBQMkqSYigxhJResC6fLWDGFhbphK67eZoqMDUvBmK/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/gx/ipfs/QmXZyBQMkqSYigxhJResC6fLWDGFhbphK67eZoqMDUvBmK/go-libp2p/p2p/host/basic/basic_host.go:284 +0x839
[livepeer@ip-172-31-56-85 bin]$ lp
I1013 01:12:21.163201    5913 livepeer.go:144] Monitor is set to 'true' by default.  If you want to disable it, use -monitor=false when starting Livepeer.
E1013 01:12:21.175787    5913 livepeernode.go:76] Cannot connect to node: dial attempt failed: <peer.ID Ta9q76> --> <peer.ID XeYaU3> dial attempt failed: dial tcp4 52.15.174.204:15000: getsockopt: connection refused
E1013 01:12:21.175811    5913 livepeer.go:178] Cannot connect to bootstrap node: dial attempt failed: <peer.ID Ta9q76> --> <peer.ID XeYaU3> dial attempt failed: dial tcp4 52.15.174.204:15000: getsockopt: connection refused
```

**Comment by ericxtang** [comment]
Yeah - been seeing this problem.  It will be address in the new testnet release in the next few weeks.

**Comment by 0x1F602** [comment]
@ericxtang What release do you expect this to go in? Can you give another issue # or more information?

**Comment by ericxtang** [comment]
Hi @beta0x64, sorry for the delay!  I think this error should be already fixed in the latest code in master, but we haven't deployed the new nodes to the testnet yet.  Planning to do that next week.

**Comment by ericxtang** [comment]
Addressed in https://github.com/livepeer/go-livepeer/releases/tag/0.1.4
