### ISSUE TITLE
Node crashes when new video immediately finishes

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#165]
```
I1017 13:51:51.254488    2682 livepeernode.go:222] Starting to transcode segment 0
I1017 13:51:51.254491    2682 livepeernode.go:226] Stream finished. Claiming work.
panic: runtime error: index out of range

goroutine 774719 [running]:
github.com/livepeer/go-livepeer/core.(*BasicClaimManager).makeRanges(0xc459676e10, 0xc42022e000, 0x0, 0xc42022e030)
	/Users/ericxtang/go/src/github.com/livepeer/go-livepeer/core/claimmanager.go:158 +0x624
github.com/livepeer/go-livepeer/core.(*BasicClaimManager).Claim(0xc459676e10, 0x207aa, 0x207aa, 0x4d2612a)
	/Users/ericxtang/go/src/github.com/livepeer/go-livepeer/core/claimmanager.go:190 +0x61
github.com/livepeer/go-livepeer/core.(*LivepeerNode).ClaimVerifyAndDistributeFees(0xc4204087e0, 0x4d54ae0, 0xc459676e10, 0x0, 0x0)
	/Users/ericxtang/go/src/github.com/livepeer/go-livepeer/core/livepeernode.go:141 +0x6e
github.com/livepeer/go-livepeer/core.(*LivepeerNode).TranscodeAndBroadcast.func2(0x0, 0x0, 0x0, 0x0, 0x1)
	/Users/ericxtang/go/src/github.com/livepeer/go-livepeer/core/livepeernode.go:228 +0x207
github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet.(*BasicSubscriber).startWorker.func1(0xc45b2ece40, 0xc4206c86e0, 0x4d534e0, 0xc456436e00, 0xc4201f3040)
	/Users/ericxtang/go/src/github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet/basic_subscriber.go:107 +0x3f1
created by github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet.(*BasicSubscriber).startWorker
	/Users/ericxtang/go/src/github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet/basic_subscriber.go:114 +0x67
exit status 2
```

**Comment by yondonfu** [comment]
I suspect this error occurs when the node tries to claim after a stream finishes really quickly and the ClaimManager has not added the receipt data yet so when the ClaimManager tries to create continuous segment ranges using makeRanges it tries to index into an empty array.

makeRanges could probably be improved to avoid this type of error, but in a recent change to the ClaimManager we also added a CanClaim function that returns true if there are any claimable segments which should mitigate this issue for now

**Comment by yondonfu** [comment]
I don't think this issue should be a problem now that the ClaimManager checks if there are any claimable segments (i.e. whether any receipt data has been added to the ClaimManager with which a continuous segment range can be created for claiming purposes)
