### ISSUE TITLE
panic in server.selectOrchestrator

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#1660]
I was just idly watching Papertrail logs and this zipped past, dropping it here, plausibly a dupe of something we have already 
```
2020/11/23 20:56:30 http: panic serving 10.42.0.31:34546: runtime error: invalid memory address or nil pointer dereference
goroutine 1016869 [running]:
net/http.(*conn).serve.func1(0xc0017d4320)
	/usr/lib/go-1.13/src/net/http/server.go:1767 +0x139
panic(0x1c67c40, 0x2e711d0)
	/usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2
github.com/livepeer/go-livepeer/server.selectOrchestrator(0xc000610580, 0xc005162480, 0x8, 0xc0006b0780, 0x107af2f, 0x0, 0x0, 0xc000d00f68, 0xc0006b0780)
	/build/server/broadcast.go:246 +0x69b
github.com/livepeer/go-livepeer/server.NewSessionManager.func1(0xc0006b0780, 0xc007378a98, 0xc0002ab2f0, 0x3462, 0x2)
	/build/server/broadcast.go:205 +0x45
github.com/livepeer/go-livepeer/server.(*BroadcastSessionsManager).refreshSessions(0xc003ab8ea0)
	/build/server/broadcast.go:144 +0x2d2
github.com/livepeer/go-livepeer/server.NewSessionManager(0xc000610580, 0xc005162480, 0x21a6de0, 0xc0011914c0, 0x0)
	/build/server/broadcast.go:212 +0x232
github.com/livepeer/go-livepeer/server.(*LivepeerServer).registerConnection(0xc000e37300, 0x21b1a60, 0xc0055b1dc0, 0xc004589db0, 0x9, 0x0)
	/build/server/mediaserver.go:531 +0x3e3
github.com/livepeer/go-livepeer/server.(*LivepeerServer).HandlePush(0xc000e37300, 0x219c3a0, 0xc000cb5960, 0xc000e3e400)
	/build/server/mediaserver.go:764 +0x840
net/http.HandlerFunc.ServeHTTP(0xc000e66810, 0x219c3a0, 0xc000cb5960, 0xc000e3e400)
	/usr/lib/go-1.13/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0xc003432940, 0x219c3a0, 0xc000cb5960, 0xc000e3e400)
	/usr/lib/go-1.13/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc000afa000, 0x219c3a0, 0xc000cb5960, 0xc000e3e400)
	/usr/lib/go-1.13/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0017d4320, 0x21a2f20, 0xc0018a5ac0)
	/usr/lib/go-1.13/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/lib/go-1.13/src/net/http/server.go:2927 +0x38e
```

**Comment by yondonfu** [comment]
Due to on-chain node talking to off-chain node. Resolved by making sure nodes are on the same network (i.e. mainnet, rinkeby, offchain). Could probably be handled more elegantly...leaving that to be addressed separately so closing this for now.
