### ISSUE TITLE
nil pointer in block watcher syncToLatestBlock

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1803]
Observed this error with an O connected to Rinkeby. There is probably a missing nil check somewhere in the block watcher code:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xb30609]

goroutine 47 [running]:
github.com/livepeer/go-livepeer/eth/blockwatch.(*Watcher).syncToLatestBlock(0xc000390360, 0x0, 0x0)
        /build/eth/blockwatch/block_watcher.go:162 +0xe9
github.com/livepeer/go-livepeer/eth/blockwatch.(*Watcher).Watch(0xc000390360, 0x1fec980, 0xc0009e2600, 0x1fcf4c0, 0xc000428300)
        /build/eth/blockwatch/block_watcher.go:123 +0x165
main.main.func6(0xc000390360, 0x1fec980, 0xc0009e2600, 0xc0009dcba0)
        /build/cmd/livepeer/livepeer.go:711 +0x45
created by main.main
        /build/cmd/livepeer/livepeer.go:710 +0x411f
```

**Comment by kyriediculous** [comment]
Right...  Good find ! If there are no blocks on the stack nil can be returned without returning an error due to the following code block in `FindLatestMiniHeader`

```
	if latestMiniHeader == nil {
		return nil, nil
	}
```
