### ISSUE TITLE
SIGSEGV in Orchestrator cgo code

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#1824]
I'm filing this because I found a segfault. But it doesn't occur at all regularly, so I'd be willing to chalk it up to bad RAM or a bad GPU or something.

```
I0401 13:08:39.058823       1 player.go:105] LPMS got HTTP request @ /stream/e0ba0b0e/720p0/19.ts 
I0401 13:08:39.059112       1 player.go:105] LPMS got HTTP request @ /stream/e0ba0b0e/360p0/19.ts 
I0401 13:08:39.074959       1 segment_rpc.go:83] Received segment manifestID=[redacted] sessionID=7bbf83ae seqNo=20 dur=1.6s 
I0401 13:08:39.074996       1 census.go:952] Logging SegmentEmerged... nonce=0 seqNo=20 duration=1.6 
I0401 13:08:39.107181       1 player.go:105] LPMS got HTTP request @ /stream/e0ba0b0e/240p0/19.ts 
I0401 13:08:39.109294       1 player.go:105] LPMS got HTTP request @ /stream/e0ba0b0e/480p0/19.ts 
I0401 13:08:39.188434       1 segment_rpc.go:123] Downloaded segment manifestID=[redacted] sessionID=7bbf83ae seqNo=20 dur=113.323455ms 
I0401 13:08:39.188483       1 census.go:1008] Logging SegmentDownloaded... nonce=0 seqNo=20 dur=113.323455ms 
I0401 13:08:39.199154       1 orchestrator.go:470] Starting to transcode segment manifestID=[redacted] sessionID=7bbf83ae seqNo=20 
I0401 13:08:39.199171       1 orchestrator.go:458] Creating new segment chan for manifestID=[redacted] sessionID=7bbf83ae 
I0401 13:08:39.199178       1 orchestrator.go:599] Starting transcode segment loop for manifestID=[redacted] sessionID=7bbf83ae 
I0401 13:08:39.199193       1 orchestrator.go:479] Submitted segment to transcode loop manifestID=[redacted] sessionID=7bbf83ae seqNo=20 
I0401 13:08:39.200163       1 lb.go:76] LB: Creating transcode session for 7bbf83ae 
I0401 13:08:39.200583       1 lb.go:111] LB: Created transcode session for 7bbf83ae_0 
I0401 13:08:39.200603       1 lb.go:187] LB: Transcode submitted for 7bbf83ae_0 
fatal error: unexpected signal during runtime execution 
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f597ac06800] 
runtime stack: 
runtime.throw(0x1de4762, 0x2a) 
	/usr/local/go/src/runtime/panic.go:1116 +0x72 
runtime.sigpanic() 
	/usr/local/go/src/runtime/signal_unix.go:726 +0x4ac 
goroutine 118516 [syscall]: 
runtime.cgocall(0x10cc150, 0xc000b37668, 0xc000b37678) 
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000b37638 sp=0xc000b37600 pc=0x4a3b5b 
github.com/livepeer/lpms/ffmpeg._Cfunc_lpms_transcode(0xc0128c4420, 0xc000518000, 0xc000b0a300, 0x4, 0xc001058130, 0xc000000000) 
	_cgo_gotypes.go:312 +0x4d fp=0xc000b37668 sp=0xc000b37638 pc=0xc321ad 
github.com/livepeer/lpms/ffmpeg.(*Transcoder).Transcode.func9(0xc0128c4420, 0xc000518000, 0xc000b0a300, 0xc000518000, 0x4, 0x4, 0xc001058130, 0xc0004b7250) 
	/go/pkg/mod/github.com/livepeer/lpms@v0.0.0-20210216144135-b4601518b202/ffmpeg/ffmpeg.go:362 +0x9c fp=0xc000b376a8 sp=0xc000b37668 pc=0xc359fc 
github.com/livepeer/lpms/ffmpeg.(*Transcoder).Transcode(0xc0128c4320, 0xc000b37e58, 0xc0109f0700, 0x4, 0x4, 0x0, 0x0, 0x0) 
	/go/pkg/mod/github.com/livepeer/lpms@v0.0.0-20210216144135-b4601518b202/ffmpeg/ffmpeg.go:362 +0xbea fp=0xc000b37da8 sp=0xc000b376a8 pc=0xc335ea 
github.com/livepeer/go-livepeer/core.(*NvidiaTranscoder).Transcode(0xc0128c4340, 0xc000d4c280, 0x2, 0x1, 0xc000d4c201) 
	/build/core/transcoder.go:82 +0x1ac fp=0xc000b37e90 sp=0xc000b37da8 pc=0x102034c 
github.com/livepeer/go-livepeer/core.(*transcoderSession).loop(0xc010a80140) 
	/build/core/lb.go:166 +0x184 fp=0xc000b37fb8 sp=0xc000b37e90 pc=0x1013fc4 
github.com/livepeer/go-livepeer/core.(*LoadBalancingTranscoder).createSession.func2(0xc010a80140, 0xc010a80180) 
	/build/core/lb.go:107 +0x2b fp=0xc000b37fd0 sp=0xc000b37fb8 pc=0x1021b8b 
runtime.goexit() 
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000b37fd8 sp=0xc000b37fd0 pc=0x510bc1 
created by github.com/livepeer/go-livepeer/core.(*LoadBalancingTranscoder).createSession 
	/build/core/lb.go:106 +0x5dc 
```

**Comment by yondonfu** [comment]
Seems to be fixed by livepeer/lpms#268
