### ISSUE TITLE
Invalid memory address error from livepeer_cli when updating orchestrator configuration

### ISSUE THREAD

**Issue by GistKen** [livepeer/go-livepeer#1953]
**Describe the bug**
When attempting to send a orchestrator configuration update via livepeer_cli, experienced an invalid memory address error.

**To Reproduce**
- Send orchestrator configuration update message via livepeer -orchestrator 

**Expected behavior**
Experienced memory address error. No transaction went through and no gas fees were taken. 

**Screenshots**
```
ERROR[07-15|04:48:28.584] Error sending HTTP POST                  url=http://localhost:7935/setOrchestratorConfig err="Post \"http://localhost:7935/setOrchestratorConfig\": EOF"

Jul 15 04:48:26 LivepeerOrchestrator geth[457]: INFO [07-15|04:48:26.703] Imported new block headers               count=1 elapsed=3.892ms   number=12,829,478 hash=cd15bd..e16d6d
Jul 15 04:48:28 LivepeerOrchestrator geth[457]: INFO [07-15|04:48:28.583] Submitted transaction                    hash=0xb32876e5c081c9601dbc85275bd2f5dbb04f10fb363a5e573c4de54cc84b5f24 from=0xb1E6Eb71b36D0817723631F25124CE0a828b054e nonce=21 recipient=0x511Bc4556D823Ae99630aE8de28b9B80Df90eA2e value=0
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: I0715 04:48:28.583913    5514 transactionManager.go:113]
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: ******************************Eth Transaction******************************
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: Invoking transaction: "transcoder". Inputs: "_rewardCut: 50000  _feeShare: 500000"  Hash: "0xb32876e5c081c9601dbc85275bd2f5dbb04f10fb363a5e573c4de54cc84b5f24".
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: ***************************************************************************
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: 2021/07/15 04:48:28 http: panic serving 127.0.0.1:46318: runtime error: invalid memory address or nil pointer dereference
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: goroutine 151 [running]:
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: net/http.(*conn).serve.func1(0xc0107d6500)
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: #011/opt/hostedtoolcache/go/1.15.5/x64/src/net/http/server.go:1801 +0x147
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: panic(0x1c445e0, 0x2bbf170)
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: #011/opt/hostedtoolcache/go/1.15.5/x64/src/runtime/panic.go:975 +0x47a
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: github.com/ethereum/go-ethereum/core/types.Sender(0x0, 0x0, 0xc00023c3f0, 0x0, 0x0, 0x0, 0xc0107c0120, 0x1bbdf40)
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: #011/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.3/core/types/transaction_signing.go:83 +0x141
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: github.com/ethereum/go-ethereum/core/types.(*Transaction).AsMessage(0xc00023c3f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: #011/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.3/core/types/transaction.go:232 +0x16e
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: github.com/livepeer/go-livepeer/eth.(*backend).SendTransaction(0xc00016a140, 0x2041c40, 0xc0000a4008, 0xc00023c3f0, 0xc04e058b82, 0xc00023c2d0)
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: #011/home/runner/work/go-livepeer/go-livepeer/eth/backend.go:83 +0xb4
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: github.com/ethereum/go-ethereum/accounts/abi/bind.(*BoundContract).transact(0xc0002b02c0, 0xc00013d2c8, 0xc0002b02c0, 0xc0109fb810, 0x44, 0x50, 0x1, 0x4, 0x0)
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: #011/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.3/accounts/abi/bind/base.go:241 +0x483
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: github.com/ethereum/go-ethereum/accounts/abi/bind.(*BoundContract).Transact(0xc0002b02c0, 0xc00013d2c8, 0x1dfc3a3, 0xa, 0xc0107e18c0, 0x2, 0x2, 0x12, 0x0, 0x0)
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: #011/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.3/accounts/abi/bind/base.go:174 +0x176
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: github.com/livepeer/go-livepeer/eth/contracts.(*BondingManagerTransactor).Transcoder(...)
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: #011/home/runner/work/go-livepeer/go-livepeer/eth/contracts/bondingManager.go:1248
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: github.com/livepeer/go-livepeer/eth/contracts.(*BondingManagerSession).Transcoder(0xc00013d290, 0xc0003b7060, 0xc0003b7080, 0x0, 0x0, 0xe)
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: #011/home/runner/work/go-livepeer/go-livepeer/eth/contracts/bondingManager.go:1255 +0xad
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: github.com/livepeer/go-livepeer/eth.(*client).Transcoder(0xc0000de000, 0xc0003b7060, 0xc0003b7080, 0x4e058b82, 0xc000183200, 0x0)
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: #011/home/runner/work/go-livepeer/go-livepeer/eth/client.go:380 +0xb8
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: github.com/livepeer/go-livepeer/server.(*LivepeerServer).cliWebServerHandlers.func7(0x203b980, 0xc0107540e0, 0xc010c07c00)
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: #011/home/runner/work/go-livepeer/go-livepeer/server/webserver.go:422 +0x786
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: net/http.HandlerFunc.ServeHTTP(0xc000364370, 0x203b980, 0xc0107540e0, 0xc010c07c00)
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: #011/opt/hostedtoolcache/go/1.15.5/x64/src/net/http/server.go:2042 +0x44
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: net/http.(*ServeMux).ServeHTTP(0x2cfad00, 0x203b980, 0xc0107540e0, 0xc010c07c00)
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: #011/opt/hostedtoolcache/go/1.15.5/x64/src/net/http/server.go:2417 +0x1ad
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: net/http.serverHandler.ServeHTTP(0xc0002f61c0, 0x203b980, 0xc0107540e0, 0xc010c07c00)
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: #011/opt/hostedtoolcache/go/1.15.5/x64/src/net/http/server.go:2843 +0xa3
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: net/http.(*conn).serve(0xc0107d6500, 0x2041c00, 0xc010f22700)
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: #011/opt/hostedtoolcache/go/1.15.5/x64/src/net/http/server.go:1925 +0x8ad
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: created by net/http.(*Server).Serve
Jul 15 04:48:28 LivepeerOrchestrator livepeer[5514]: #011/opt/hostedtoolcache/go/1.15.5/x64/src/net/http/server.go:2969 +0x36c
Jul 15 04:48:36 LivepeerOrchestrator geth[457]: INFO [07-15|04:48:36.116] Imported new block headers               count=1 elapsed=4.986ms   number=12,829,479 hash=07c36b..ed9e71

Jul 15 04:53:28 LivepeerOrchestrator geth[457]: INFO [07-15|04:53:28.908] Submitted transaction                    hash=0x3c0ecc0409f1bca358c07134de6823630587cf0c40a24f7b5de4d9e080e13ef3 from=0xb1E6Eb71b36D0817723631F25124CE0a828b054e nonce=21 recipient=0x511Bc4556D823Ae99630aE8de28b9B80Df90eA2e value=0
Jul 15 04:53:28 LivepeerOrchestrator livepeer[5514]: I0715 04:53:28.909543    5514 transactionManager.go:186]
Jul 15 04:53:28 LivepeerOrchestrator livepeer[5514]: ******************************Eth Transaction******************************
Jul 15 04:53:28 LivepeerOrchestrator livepeer[5514]: Replacement transaction: "transcoder".  Gas Price: 32000000000
Jul 15 04:53:28 LivepeerOrchestrator livepeer[5514]: Transaction Failed: <nil>
Jul 15 04:53:28 LivepeerOrchestrator livepeer[5514]: ***************************************************************************
```
** Livepeer Version
Compiler: gc Arch amd64 OS linux Go version go1.15.5
Livepeer version: 0.5.18-d187acd2

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS (GNU/Linux 5.8.0-1038-aws x86_64)

**Additional context**
The changes were reflected on the explorer but the transaction failed?

**Comment by yondonfu** [comment]
Thanks for the report @Makalfo!

Looks like the latest commit on the master branch contains a bug where a [signer is missing during a configuration step](https://github.com/livepeer/go-livepeer/blob/d187acd2caa12cf1fb24b76ceeb3d46027b4a3a9/cmd/livepeer/livepeer.go#L415). Will get this fixed!

**Comment by yondonfu** [comment]
@Makalfo 

> The changes were reflected on the explorer but the transaction failed?

To clarify why this happened - the first tx failed due to the bug that was just fixed (on the master branch now), but the node retried the tx in the background and that logic did not include the bug that affected the first tx which is why the changes were reflected in the explorer.

**Comment by GistKen** [comment]
Thanks! :)
