### ISSUE TITLE
Claim Causes Transcoder to Crash

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#217]
Transcoder crashed after simple transcoding workflow.  This doesn't happen all the time.

```
I1205 21:25:15.231611    4537 basic_subscriber.go:95] Subscriber worker inserted segment: 68 - took 15.674982971s in total, 15.674982025s waiting for data
I1205 21:25:15.231714    4537 livepeernode.go:205] Starting to transcode segment 68
I1205 21:25:15.233740    4537 livepeernode.go:239] Decoding of segment took 503.584µs
I1205 21:25:16.125953    4537 basic_hls_videostream.go:83] Adding segment: 1220ec2444554f67c8e86b6b6def815989397e810e19f14e958176248d11d1e9649488826199e6f0380aff6a4027b666e43271b19602749abc87e27fd92f56299c9aP240p30fps16x9_67.ts
I1205 21:25:16.554256    4537 basic_network.go:332] Received a message 1 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I1205 21:25:16.554292    4537 basic_subscriber.go:99] Done with subscription, sending CancelSubMsg
I1205 21:25:16.554422    4537 livepeernode.go:205] Starting to transcode segment 0
I1205 21:25:16.554433    4537 livepeernode.go:209] Stream finished. Claiming work.
panic: runtime error: makeslice: len out of range

goroutine 74703 [running]:
github.com/livepeer/go-livepeer/core.(*BasicClaimManager).Claim(0xc421006870, 0x44e92b, 0x1a08cf9, 0x38dfe)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/core/claimmanager.go:198 +0x14a
github.com/livepeer/go-livepeer/core.(*LivepeerNode).ClaimVerifyAndDistributeFees(0xc420402360, 0x1c9ac40, 0xc421006870, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/core/livepeernode.go:127 +0x6a
github.com/livepeer/go-livepeer/core.(*LivepeerNode).TranscodeAndBroadcast.func2(0x0, 0x0, 0x0, 0x0, 0x1)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/core/livepeernode.go:211 +0x207
created by github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet.(*BasicSubscriber).startWorker.func1
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet/basic_subscriber.go:101 +0x3dc
```

**Comment by ericxtang** [comment]
Out of date
