### ISSUE TITLE
fast verification panic: lpms_compare_sign_bybuffer

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#2175]
Got this after flipping on verification on secondary broadcasters - partial stack trace here: https://gist.github.com/iameli/ab0fc42f239eeff1253759444dcd590a

Important bit:
```
fatal error: unexpected signal during runtime execution
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:726 +0x4ac

goroutine 1327 [syscall]:
runtime.cgocall(0x1095490, 0xc002482ac8, 0x1)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc002482a98 sp=0xc002482a60 pc=0x47f3db
github.com/livepeer/lpms/ffmpeg._Cfunc_lpms_compare_sign_bybuffer(0xc0001f2800, 0xc000000121, 0xc0002b3e00, 0x121, 0x0)
	_cgo_gotypes.go:283 +0x4d fp=0xc002482ac8 sp=0xc002482a98 pc=0xbe42ed
github.com/livepeer/lpms/ffmpeg.CompareSignatureByBuffer.func1(0xc0001f2800, 0xc0001f2800, 0x121, 0x200, 0xc0002b3e00, 0xc0002b3e00, 0x121, 0x200, 0x1e40078)
	/go/pkg/mod/github.com/livepeer/lpms@v0.0.0-20211208221036-644122186d24/ffmpeg/ffmpeg.go:152 +0x91 fp=0xc002482b00 sp=0xc002482ac8 pc=0xbe9371
github.com/livepeer/lpms/ffmpeg.CompareSignatureByBuffer(0xc0001f2800, 0x121, 0x200, 0xc0002b3e00, 0x121, 0x200, 0x200, 0x0, 0x0)
	/go/pkg/mod/github.com/livepeer/lpms@v0.0.0-20211208221036-644122186d24/ffmpeg/ffmpeg.go:152 +0x85 fp=0xc002482b58 sp=0xc002482b00 pc=0xbe4c25
github.com/livepeer/go-livepeer/server.(*BroadcastSessionsManager).chooseResults(0xc014204e40, 0x1e4eb60, 0xc01e228330, 0xc0135102a0, 0x3, 0xc0198632c0, 0xf84f6eb78f204b0c, 0xc019863201, 0xc0135102a0)
	/build/server/broadcast.go:506 +0x3e5 fp=0xc002482cd8 sp=0xc002482b58 pc=0x102e9a5
```

**Comment by hthillman** [comment]
@iameli @darkdarkdragon I'm on an issue triage bender! I've added the labels I think are appropriate - can you confirm?

**Comment by iameli** [comment]
Yep, definitely!

**Comment by yondonfu** [comment]
Looks like this hasn't been completely addressed as we observed what appears to be the same type of panic on a call to `ffmpeg.CompareSignatureByBuffer`:

```
github.com/livepeer/lpms/ffmpeg.CompareSignatureByBuffer.func1(0xc000392000, 0xc000392000, 0x1245, 0x1e00, 0xc000448000, 0xc000448000, 0x1245, 0x1e00, 0x1e40678)
_cgo_gotypes.go:282 +0x4d fp=0xc000a4cab0 sp=0xc000a4ca80 pc=0xbe372d
github.com/livepeer/lpms/ffmpeg._Cfunc_lpms_compare_sign_bybuffer(0xc000392000, 0xc000001245, 0xc000448000, 0x1245, 0x0)
/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000a4ca80 sp=0xc000a4ca48 pc=0x47e81b
```

**Comment by yondonfu** [comment]
https://github.com/livepeer/lpms/pull/296 -> PR from @darkdarkdragon that seems to be doing some fuzz testing of the CompareSignatureByBuffer function to identify failure cases.
