### ISSUE TITLE
Node crash due to concurrent map read/write in basic_network.go

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#246]
Looks like `BasicVideoNetwork.msgChans[]` is being accessed without a lock in `handleMasterPlaylistDataMsg()` causing the node to crash on the gateway server.

```
I0102 21:26:45.464145    9419 basic_network.go:452] Received a message 6 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0102 21:26:45.464257    9419 basic_network.go:452] Received a message 6 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0102 21:26:45.464330    9419 basic_network.go:452] Received a message 6 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
fatal error: concurrent map read and map write

goroutine 8612 [running]:
runtime.throw(0x11d77a0, 0x21)
        /usr/lib/go-1.8/src/runtime/panic.go:596 +0x95 fp=0xc4214079e0 sp=0xc4214079c0
runtime.mapaccess2_faststr(0xff51c0, 0xc4202c8060, 0xc420dd1ef0, 0x86, 0x86, 0x10)
        /usr/lib/go-1.8/src/runtime/hashmap_fast.go:326 +0x50a fp=0xc421407a40 sp=0xc4214079e0
github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet.handleMasterPlaylistDataMsg(0xc4202be740, 0xc420dd1e60, 0x84, 0x0, 0x0, 0x1, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet/basic_network.go:797 +0x87 fp=0xc421407ad8 sp=0xc421407a40
github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet.streamHandler(0xc4202be740, 0xc4202d9b30, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet/basic_network.go:511 +0x1009 fp=0xc421407ef8 sp=0xc421407ad8
github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet.(*BasicVideoNetwork).SetupProtocol.func1(0x1caacc0, 0xc4201c30c0)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet/basic_network.go:431 +0x5f fp=0xc421407f60 sp=0xc421407ef8
github.com/livepeer/go-livepeer/vendor/gx/ipfs/Qmbgce14YTWE2qhE49JVvTBPaHTyz3FaFmqQPyuZAz6C28/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1(0xc4201c3080, 0x15, 0x7f6bbd288620, 0xc4201c30c0, 0x4238f41, 0xc42067ebc
0)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/gx/ipfs/Qmbgce14YTWE2qhE49JVvTBPaHTyz3FaFmqQPyuZAz6C28/go-libp2p/p2p/host/basic/basic_host.go:320 +0x9d fp=0xc421407fb0 sp=0xc421407f60
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc421407fb8 sp=0xc421407fb0
created by github.com/livepeer/go-livepeer/vendor/gx/ipfs/Qmbgce14YTWE2qhE49JVvTBPaHTyz3FaFmqQPyuZAz6C28/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/gx/ipfs/Qmbgce14YTWE2qhE49JVvTBPaHTyz3FaFmqQPyuZAz6C28/go-libp2p/p2p/host/basic/basic_host.go:284 +0x7d2

goroutine 1 [select, 120 minutes]:
main.main()
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/cmd/livepeer/livepeer.go:363 +0x17bd
```

**Comment by j0sh** [comment]
Just saw this again. Got a full log, here it is happening in the relayer.

https://gist.github.com/j0sh/b4d2f0abcea12bd48c35992a763e7466
