### ISSUE TITLE
Div by 0 in roundsservice shouldInitializeRound()

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#253]
I started the new node with the `-transcoder` flag, and got a crash with the div by 0 error...

```
panic: division by zero

goroutine 361 [running]:
math/big.nat.div(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4211cb200, 0x4, 0x8, 0x0, ...)
        /usr/lib/go-1.8/src/math/big/nat.go:525 +0x482
math/big.(*Int).QuoRem(0xc420585bf8, 0xc420585d00, 0xc4211ec0c0, 0xc420585ce0, 0x4, 0x8)
        /usr/lib/go-1.8/src/math/big/int.go:227 +0xbf
math/big.(*Int).Mod(0xc420585ce0, 0xc420585d00, 0xc4211ec0c0, 0x20)
        /usr/lib/go-1.8/src/math/big/int.go:258 +0x17d
github.com/livepeer/go-livepeer/eth/eventservices.(*RoundsService).shouldInitializeRound(0xc4210bba00, 0xc420585e10, 0xc42119b380, 0xf54f0e7178e8cf9b, 0xf5bf567a44642874, 0x8fae18885763ce03, 0xfc9d7030aecaa62b, 0xf1e520, 0xc4211ea000, 0xf54f0e7178e8cf9b)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/eth/eventservices/roundservice.go:141 +0x2bd
github.com/livepeer/go-livepeer/eth/eventservices.(*RoundsService).tryInitializeRound(0xc4210bba00, 0xc42119b380, 0xf54f0e7178e8cf9b, 0xf5bf567a44642874, 0x8fae18885763ce03, 0xfc9d7030aecaa62b, 0xc420e627a8, 0x2, 0x2)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/eth/eventservices/roundservice.go:89 +0x1a6
github.com/livepeer/go-livepeer/eth/eventservices.(*RoundsService).Start.func1(0xc4211ea000, 0xc4210ca6c0, 0xc420e62710, 0xc420e62600)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/eth/eventservices/roundservice.go:43 +0x97
github.com/livepeer/go-livepeer/eth.watchBlocks(0x1a20320, 0xc42043be60, 0xc4210ca540, 0xc4210bed00)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/eth/eventmonitor.go:137 +0x107
created by github.com/livepeer/go-livepeer/eth.(*eventMonitor).SubscribeNewBlock
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/eth/eventmonitor.go:99 +0xde
```

**Comment by dob** [comment]
Closed by #254
