### ISSUE TITLE
Too many open files, index out of range, error during verification

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#256]
My transcoding node received 121 segments, and then made a claim for segments 1-121. Segment 38 got challenged. The node then gave a `too many open files` error with `index out of range`.

```
I0110 21:23:31.183729   28507 basic_network.go:473] Received a message 0 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0110 21:23:33.531722   28507 livepeernode.go:222] Finished transcoding segment 118, overall took 2.347943638s


I0110 21:23:39.495980   28507 basic_network.go:473] Received a message 0 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0110 21:23:41.882023   28507 livepeernode.go:222] Finished transcoding segment 119, overall took 2.385991098s


I0110 21:23:45.013084   28507 jobservice.go:145] Making the first claim
I0110 21:23:47.925619   28507 basic_network.go:473] Received a message 0 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0110 21:23:50.367812   28507 livepeernode.go:222] Finished transcoding segment 120, overall took 2.442133758s


I0110 21:23:56.025802   28507 claimmanager.go:257] Submitted transcode claim for segments 0 - 119
I0110 21:23:56.027855   28507 eventmonitor.go:144] Done watching
I0110 21:23:56.028988   28507 helpers.go:82] Waiting 1 blocks...
I0110 21:23:56.102402   28507 basic_network.go:473] Received a message 0 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0110 21:23:58.782422   28507 livepeernode.go:222] Finished transcoding segment 121, overall took 2.679964784s


I0110 21:24:01.436157   28507 claimmanager.go:310] Segment 38 challenged for verification
I0110 21:24:04.543789   28507 basic_network.go:473] Received a message 0 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
E0110 21:24:04.547649   28507 ffmpeg_segment_transcoder.go:40] Transcoder cannot write file: open /home/ubuntu/.lpData/c9f4651b427b8d7434b5.ts: too many open files
E0110 21:24:04.547670   28507 livepeernode.go:232] Error transcoding seg: 12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a98ef34eedfd9ad02cba4661bb17dda8beb7bfeaf9819c88ba9f16137922b6beb56P720p30fps16x9_122.ts - open /home/ubuntu/.lpData/c9f4651b427b8d7434b5.ts: too many open files
panic: runtime error: index out of range

goroutine 1616305 [running]:
github.com/livepeer/go-livepeer/core.(*LivepeerNode).transcodeAndBroadcastSeg(0xc4205d64d0, 0xc42d7e3f58, 0xc4448f2820, 0x41, 0x41, 0x1a2cb20, 0xc43bc67b80, 0x1a1aee0, 0xc43bcb4340, 0xc43bca9640, ...)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/core/livepeernode.go:240 +0x903
github.com/livepeer/go-livepeer/core.(*LivepeerNode).TranscodeAndBroadcast.func1(0x7a, 0xc428fe0000, 0x2e23a0, 0x2e23a0, 0xc42336b500)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/core/livepeernode.go:220 +0x5ab
created by github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet.(*BasicSubscriber).startWorker.func1
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/github.com/livepeer/go-livepeer-basicnet/basic_subscriber.go:115 +0x1d9
```

**Comment by dob** [comment]
This actually may have had nothing to do with verification, as we saw it during general transcoding as well.

**Comment by ericxtang** [comment]
https://github.com/livepeer/go-livepeer/pull/263 gets rid of the panic, but we still need to figure out if there are cases when we are not properly closing file handles.

**Comment by ericxtang** [comment]
Closing because we haven't seen this since the fix.
