### ISSUE TITLE
go-livepeer should crash if it has a nil orchestrator pool

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#2560]
Encountered this problem with a mainnet broadcaster today:

```
INFO: E0804 16:06:14.773260     194 starter.go:975] Could not create orchestrator pool with DB cache: Could not refresh DB list of orchestrators: unsupported block number 19384378
```

I'm not sure of the root cause. We saw problems very similar to this [when Infura was omitting their block number](https://community.infura.io/t/arbitrum-eth-getblockbynumber-omits-l1blocknumber-field/5462/2). So root cause still under investigation.

That said, **we should crash if we find ourselves in this state**. If you try and transcode without an orchestrator pool, we just segfault over and over again:
```
2022/08/04 15:53:15 http: panic serving 127.0.0.1:42912: runtime error: invalid memory address or nil pointer dereference
goroutine 1423 [running]:
net/http.(*conn).serve.func1()
	/opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:1802 +0xb9
panic({0x367c80, 0x23c7570})
	/opt/hostedtoolcache/go/1.17.12/x64/src/runtime/panic.go:1047 +0x266
github.com/livepeer/go-livepeer/discovery.(*DBOrchestratorPoolCache).nextRound(0x0)
	/home/runner/work/go-livepeer/go-livepeer/discovery/db_discovery.go:342 +0x1d
github.com/livepeer/go-livepeer/discovery.(*DBOrchestratorPoolCache).Size(0x0)
	/home/runner/work/go-livepeer/go-livepeer/discovery/db_discovery.go:156 +0x3b
github.com/livepeer/go-livepeer/discovery.(*DBOrchestratorPoolCache).SizeWith(0x10, 0xc0007aade8)
	/home/runner/work/go-livepeer/go-livepeer/discovery/db_discovery.go:165 +0x32
github.com/livepeer/go-livepeer/server.NewSessionManager({0x7066c0, 0xc013d14120}, 0xc0002bd4a0, 0xc0005ad950, 0x0)
	/home/runner/work/go-livepeer/go-livepeer/server/broadcast.go:374 +0xe9
github.com/livepeer/go-livepeer/server.(*LivepeerServer).registerConnection(0xc010dbcfc0, {0x7066c0, 0xc010dd41b0}, {0x71edd8, 0xc00031c540}, 0xc0007ab0f0, {0x0}, 0xc0001b52c0)
	/home/runner/work/go-livepeer/go-livepeer/server/mediaserver.go:542 +0x585
github.com/livepeer/go-livepeer/server.(*LivepeerServer).HandlePush(0xc010dbcfc0, {0x6fcd58, 0xc00098a000}, 0xc010da4400)
	/home/runner/work/go-livepeer/go-livepeer/server/mediaserver.go:878 +0x1694
net/http.HandlerFunc.ServeHTTP(0x7f295c7b9e60, {0x6fcd58, 0xc00098a000}, 0xc00098a000)
	/opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0, {0x6fcd58, 0xc00098a000}, 0xc010da4400)
	/opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0x6fac40}, {0x6fcd58, 0xc00098a000}, 0xc010da4400)
	/opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc000a2a0a0, {0x7066c0, 0xc010d564e0})
	/opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.17.12/x64/src/net/http/server.go:3034 +0x4e8
```

That's bad. Crashing is preferable to continuing to run in a completely broken state.

**Comment by yondonfu** [comment]
Flagging that https://github.com/livepeer/go-livepeer/pull/2563 should address the root cause of this issue which is the `unsuported block number` error encountered while creating the orchestrator pool on startup. With that being said, it might still make sense to crash/exit the node earlier if it tries to transcode without an orchestrator pool.

**Comment by iameli** [comment]
This just caused some stuck transcoding in the pipeline.
