### ISSUE TITLE
panic: invalid argument to Intn

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#2572]
```
2022/08/30 16:54:47 http: panic serving 10.42.3.11:49366: invalid argument to Intn
--
  |   | goroutine 43991 [running]:
  |   | net/http.(*conn).serve.func1()
  |   | /usr/local/go/src/net/http/server.go:1802 +0xb9
  |   | panic({0x2fdf80, 0x8431e0})
  |   | /usr/local/go/src/runtime/panic.go:1047 +0x266
  |   | math/rand.(*Rand).Intn(0x87d160, 0xc0015ea090)
  |   | /usr/local/go/src/math/rand/rand.go:168 +0x65
  |   | math/rand.Intn(...)
  |   | /usr/local/go/src/math/rand/rand.go:337
  |   | github.com/livepeer/go-livepeer/server.transcodeSegment({0x87d160, 0xc0015ea090}, 0xc00016ba80, 0xc001a22e80, {0xc001690920, 0xb}, 0x541b12, 0x0)
  |   | /src/server/broadcast.go:1023 +0x6de
  |   | github.com/livepeer/go-livepeer/server.processSegment({0x87d160, 0xc0015ea090}, 0xc00016ba80, 0xc001a22e80, 0xc001a1e250)
  |   | /src/server/broadcast.go:872 +0x130a
  |   | github.com/livepeer/go-livepeer/server.(*LivepeerServer).HandlePush(0xc00156e240, {0x872998, 0xc0014f80e0}, 0xc000358c00)
  |   | /src/server/mediaserver.go:987 +0x1fca
  |   | net/http.HandlerFunc.ServeHTTP(0x0, {0x872998, 0xc0014f80e0}, 0xc0014f80e0)
  |   | /usr/local/go/src/net/http/server.go:2047 +0x2f
  |   | net/http.(*ServeMux).ServeHTTP(0x0, {0x872998, 0xc0014f80e0}, 0xc000358c00)
  |   | /usr/local/go/src/net/http/server.go:2425 +0x149
  |   | net/http.serverHandler.ServeHTTP({0x870358}, {0x872998, 0xc0014f80e0}, 0xc000358c00)
  |   | /usr/local/go/src/net/http/server.go:2879 +0x43b
  |   | net/http.(*conn).serve(0xc0010e0140, {0x87d160, 0xc001e04bd0})
  |   | /usr/local/go/src/net/http/server.go:1930 +0xb08
  |   | created by net/http.(*Server).Serve
  |   | /usr/local/go/src/net/http/server.go:3034 +0x4e8
```
Context: https://eu-metrics-monitoring.livepeer.live/grafana/explore?orgId=1&left=%5B%221661878485149%22,%221661878496256%22,%22Loki%22,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D~%5C%22staging-livepeer-broadcaster.%2B%5C%22,pod%3D%5C%22staging-livepeer-broadcaster-26aeimquy-69f87b45f4-77x2h%5C%22%7D%22%7D%5D

**Comment by yondonfu** [comment]
Closed by #2604
