### ISSUE TITLE
Panic: invalid memory address in usingVerified

### ISSUE THREAD

**Issue by oscar-davids** [livepeer/go-livepeer#2590]
```
github.com/livepeer/go-livepeer/server.(*LivepeerServer).HandlePush(0xc01a5e3b80, {0x872c18, 0xc0014449a0}, 0xc00171f200)
	/src/server/mediaserver.go:596 +0xc5
github.com/livepeer/go-livepeer/server.countStreamsWithFastVerificationEnabled(0x36e6a0)
	/src/server/broadcast.go:674 +0x38
github.com/livepeer/go-livepeer/server.(*BroadcastSessionsManager).usingVerified(0xc000bb4fd8)
	/usr/local/go/src/runtime/panic.go:1047 +0x266
panic({0x386a40, 0x2729410})
	/usr/local/go/src/net/http/server.go:1802 +0xb9
net/http.(*conn).serve.func1()
goroutine 19837 [running]:
2022/09/16 16:48:23 http: panic serving 10.42.1.98:57572: runtime error: invalid memory address or nil pointer dereference

```
Context: https://eu-metrics-monitoring.livepeer.monster/grafana/explore?orgId=1&left=%5B%221663347445000%22,%221663347925000%22,%22Loki%22,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D~%5C%22staging-livepeer-broadcaster.%2B%5C%22%7D%20%7C~%20%5C%22panic%5C%22%22,%22resolution%22:1%7D%5D

**Comment by yondonfu** [comment]
Closed by #2603
