### ISSUE TITLE
panic: duplicate fd

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#289]
```
E0126 15:28:06.672526   17691 peerCache.go:79] Error writing connection to file system
panic: duplicate fd

goroutine 48 [running]:
github.com/livepeer/go-livepeer/vendor/gx/ipfs/QmS4L8WB9RLZLu9YbS19cHJVjQnuvTyGaGKs75DtmX4Jyo/go-reuseport/singlepoll.worker()
	/home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/gx/ipfs/QmS4L8WB9RLZLu9YbS19cHJVjQnuvTyGaGKs75DtmX4Jyo/go-reuseport/singlepoll/linux.go:133 +0x74a
created by github.com/livepeer/go-livepeer/vendor/gx/ipfs/QmS4L8WB9RLZLu9YbS19cHJVjQnuvTyGaGKs75DtmX4Jyo/go-reuseport/singlepoll.PollPark.func1
	/home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/gx/ipfs/QmS4L8WB9RLZLu9YbS19cHJVjQnuvTyGaGKs75DtmX4Jyo/go-reuseport/singlepoll/linux.go:39 +0x64
```

Seen on a crashed transcoder node that had been transcoding segments for a stream, but failing to so for every segment:

```
I0126 15:27:48.152712   17691 basic_network.go:480] Received a message 0 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0126 15:27:48.152767   17691 basic_subscriber.go:116] Subscriber worker inserted segment: 107 - took 8.817276385s in total, 8.817275514s waiting for data
I0126 15:27:48.152786   17691 livepeernode.go:176] Starting to transcode segment 107
I0126 15:27:48.155983   17691 livepeernode.go:229] Decoding of segment took 927.879µs
E0126 15:27:48.157169   17691 ffmpeg_segment_transcoder.go:53] Cannot start ffmpeg command: open /dev/null: too many open files
E0126 15:27:48.157181   17691 livepeernode.go:242] Error transcoding seg: 1220268142a0067351838210365727bb8dde09478607917e84fe5f55bd858daae38e10f41e20eb6b9fb10c86e0b81469c23dbf0e7aeb6048733664b82ccf0de349c2P720p30fps16x9_107.ts - open /dev/null: too many open files
I0126 15:27:48.157189   17691 livepeernode.go:231] Encoding and broadcasting of segment 107 took 2.135513ms
I0126 15:27:48.157197   17691 livepeernode.go:232] Finished transcoding segment 107, overall took 4.405835ms


I0126 15:27:56.375164   17691 basic_network.go:480] Received a message 0 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0126 15:27:56.375239   17691 basic_subscriber.go:116] Subscriber worker inserted segment: 108 - took 8.222460926s in total, 8.222460184s waiting for data
I0126 15:27:56.375266   17691 livepeernode.go:176] Starting to transcode segment 108
I0126 15:27:56.378619   17691 livepeernode.go:229] Decoding of segment took 911.845µs
E0126 15:27:56.378669   17691 ffmpeg_segment_transcoder.go:40] Transcoder cannot write file: open /home/ubuntu/.lpData2/3071fe2c63e76ec1e170.ts: too many open files
E0126 15:27:56.378678   17691 livepeernode.go:242] Error transcoding seg: 1220268142a0067351838210365727bb8dde09478607917e84fe5f55bd858daae38e10f41e20eb6b9fb10c86e0b81469c23dbf0e7aeb6048733664b82ccf0de349c2P720p30fps16x9_108.ts - open /home/ubuntu/.lpData2/3071fe2c63e76ec1e170.ts: too many open files
I0126 15:27:56.378696   17691 livepeernode.go:231] Encoding and broadcasting of segment 108 took 990.84µs
I0126 15:27:56.378706   17691 livepeernode.go:232] Finished transcoding segment 108, overall took 3.434138ms


I0126 15:28:04.596787   17691 basic_network.go:480] Received a message 0 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0126 15:28:04.596856   17691 basic_subscriber.go:116] Subscriber worker inserted segment: 109 - took 8.221599749s in total, 8.221598211s waiting for data
I0126 15:28:04.596877   17691 livepeernode.go:176] Starting to transcode segment 109
I0126 15:28:04.600263   17691 livepeernode.go:229] Decoding of segment took 980.995µs
E0126 15:28:04.600314   17691 ffmpeg_segment_transcoder.go:40] Transcoder cannot write file: open /home/ubuntu/.lpData2/f55988fcb72b6fb12990.ts: too many open files
E0126 15:28:04.600321   17691 livepeernode.go:242] Error transcoding seg: 1220268142a0067351838210365727bb8dde09478607917e84fe5f55bd858daae38e10f41e20eb6b9fb10c86e0b81469c23dbf0e7aeb6048733664b82ccf0de349c2P720p30fps16x9_109.ts - open /home/ubuntu/.lpData2/f55988fcb72b6fb12990.ts: too many open files
I0126 15:28:04.600328   17691 livepeernode.go:231] Encoding and broadcasting of segment 109 took 1.048509ms
I0126 15:28:04.600335   17691 livepeernode.go:232] Finished transcoding segment 109, overall took 3.453012ms
```

**Comment by ericxtang** [comment]
Haven't seen this in a while.  I'm guessing the ipfs upgrade solved this issue?  (Could also be because of file limit).  If we can't reproduce the issue, let's close it.

**Comment by ericxtang** [comment]
Closing because no activity.
