### ISSUE TITLE
Transcoder Crash `slice bounds out of range`

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#342]
After a few consecutive transcoding jobs, the node crashes with 

```

I0322 23:42:50.379424   31851 jobservice.go:113] Transcoder got job 624 - strmID: , tData: , config: { [] true 624}
E0322 23:42:50.379470   31851 basic_subscriber.go:69] Error extracting node id from streamID:
panic: runtime error: slice bounds out of range

goroutine 455 [running]:
github.com/livepeer/go-livepeer/core.(*StreamID).GetNodeID(...)
        /home/vagrant/go/src/github.com/livepeer/go-livepeer/core/streamdata.go:44
github.com/livepeer/go-livepeer/eth/eventservices.(*JobService).doTranscode(0xc4208632f0, 0xc42f59b200, 0xc42f59b201, 0x0, 0x0)
        /home/vagrant/go/src/github.com/livepeer/go-livepeer/eth/eventservices/jobservice.go:130 +0xd49
github.com/livepeer/go-livepeer/eth/eventservices.(*JobService).Start.func1(0x2fbc10bb4595200a, 0xcf5e7999263a7178, 0x2d7676ea, 0xc42bf93f80, 0x2, 0x4, 0xc427101ba0, 0x182, 0x182, 0x1e3453, ...)
        /home/vagrant/go/src/github.com/livepeer/go-livepeer/eth/eventservices/jobservice.go:62 +0x2a1
github.com/livepeer/go-livepeer/eth.(*eventMonitor).watchLogs(0xc420309920, 0x14b3081, 0x6, 0xc420730d90, 0xc42091e120)
        /home/vagrant/go/src/github.com/livepeer/go-livepeer/eth/eventmonitor.go:244 +0x2fd
created by github.com/livepeer/go-livepeer/eth.(*eventMonitor).SubscribeNewJob
        /home/vagrant/go/src/github.com/livepeer/go-livepeer/eth/eventmonitor.go:170 +0x6ca
```

**Comment by ericxtang** [comment]
It seems like the job we got from the blockchain was empty.  This could be because we got an empty response in https://github.com/livepeer/go-livepeer/blob/6b1d9304951b7568cd3f7e079a5c58a8b9dd9091/eth/eventservices/jobservice.go#L49

We can add a retry loop here to make sure we are actually getting good data back.  (This is dependent on https://github.com/livepeer/go-livepeer/pull/338)
