### ISSUE TITLE
Separate DB handles for each goroutine

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#424]
Concurrent accesses with the same DB handle may lead to "database is locked" and a crash.

We need use a fresh DB handle for each goroutine that may access the DB.

```
I0509 09:25:34.971865   11844 db.go:469] Inserting claim for job 515
I0509 09:25:34.973706   11844 db.go:469] Inserting claim for job 516
I0509 09:25:34.974057   11844 db.go:486] Guessed claim ID to be 0 for job 516
I0509 09:25:34.974440   11844 db.go:486] Guessed claim ID to be 0 for job 515
E0509 09:25:34.974686   11844 db.go:489] Unable to insert claim database is locked
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x49d0b9a]

goroutine 1175168 [running]:
github.com/livepeer/go-livepeer/eth.(*BasicClaimManager).ClaimVerifyAndDistributeFees(0xc42e580fd0, 0x1, 0x0)
	/Users/josh/Livepeer/node/src/github.com/livepeer/go-livepeer/eth/claimmanager.go:342 +0x12da
github.com/livepeer/go-livepeer/eth/eventservices.(*JobService).doTranscode.func1(0xc421d03440, 0x0, 0xc4213e8ed0, 0x0)
	/Users/josh/Livepeer/node/src/github.com/livepeer/go-livepeer/eth/eventservices/jobservice.go:173 +0xd3
github.com/livepeer/go-livepeer/eth.(*eventMonitor).watchBlocks(0xc420444e20, 0xc43414eb00, 0x13, 0x5702940, 0xc43a2e6bd0, 0xc435700c60, 0xc42ae26e00, 0xc42678bb00)
	/Users/josh/Livepeer/node/src/github.com/livepeer/go-livepeer/eth/eventmonitor.go:262 +0x264
created by github.com/livepeer/go-livepeer/eth.(*eventMonitor).SubscribeNewBlock
	/Users/josh/Livepeer/node/src/github.com/livepeer/go-livepeer/eth/eventmonitor.go:202 +0x32d
```

**Comment by yondonfu** [comment]
Haven't seen this issue in practice and the codebase has changed a bunch since this point so closing for now. Can re-open issue if this shows up.
