### ISSUE TITLE
Broadcast node panic and SIGSEGV in gotRTMPStreamHandler

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#518]
**Describe the bug**
I started a job, and three of my segments were consumed by the transcoder, before my node crashed with the following error:

```
I0817 16:00:16.365024   18497 webserver.go:73] Transcode Job Price: 20000000000000, Transcode Job Type: [{P720p30fps16x9 4000k 30 1280x720 16:9} {P360p30fps4x3 1000k 30 480x360 4:3} {P576p30fps16x9 1500k 30 1024x576 16:9}]
I0817 16:00:54.596138   18497 mediaserver.go:416] 

Video Created With ManifestID: e005c3a32f92a4a6685f967b7d5523652b05c6b72262248b86a7e2db4c6eb2df

I0817 16:00:55.863146   18497 base.go:207] 
******************************Eth Transaction******************************

Invoking transaction: "job".  Hash: "0xf915686148f4fda45408b7568e4cbac3f629ff842559003a606768f0a6c090c5".  Params: [e005c3a32f92a4a6685f967b7d5523652b05c6b72262248b86a7e2db4c6eb2dfP720p30fps16x9 49d54ea95ecf4b52b60382a0 20000000000000 2836822] 

***************************************************************************
E0817 16:01:09.606942   18497 client.go:856] Error getting block by number 2831064: not found. retrying...
E0817 16:01:10.713016   18497 client.go:856] Error getting block by number 2831064: not found. retrying...
E0817 16:01:11.772407   18497 client.go:856] Error getting block by number 2831064: not found. retrying...
E0817 16:01:12.833846   18497 client.go:856] Error getting block by number 2831064: not found. retrying...
E0817 16:01:12.833870   18497 client.go:863] BlockByNumber failed: not found
E0817 16:01:12.833876   18497 broadcaster.go:96] Retrying transcoder assignment lookup because of not found
I0817 16:01:15.359218   18497 broadcaster.go:115] Created broadcast job. Id: 3225, Price: 20000000000000, Transcoder:0x94107cB2261e722f9F4908115546Eeee17dECada, Type: 49d54ea95ecf4b52b60382a0
I0817 16:01:15.577366   18497 rpc.go:362] Connecting RPC to https://13.58.143.99:4433
E0817 16:01:21.088362   18497 rpc.go:378] Could not get transcoder: rpc error: code = Unknown desc = Invalid transcoder request (Transcoder was not assigned)
E0817 16:01:21.088421   18497 mediaserver.go:162] Unable to start broadcast client for 3225
I0817 16:01:21.713024   18497 rpc.go:362] Connecting RPC to https://13.58.143.99:4433
I0817 16:01:23.589069   18497 rpc.go:417] Submitting segment 5 : 607240 bytes
I0817 16:01:24.085302   18497 rpc.go:439] Uploaded segment 5
I0817 16:01:28.224672   18497 rpc.go:417] Submitting segment 6 : 611564 bytes
I0817 16:01:28.395755   18497 rpc.go:439] Uploaded segment 6
E0817 16:01:31.598093   18497 rpc.go:448] Unable to read response body for segment 5 : net/http: request canceled (Client.Timeout exceeded while reading body)
I0817 16:01:31.940986   18497 rpc.go:417] Submitting segment 7 : 610248 bytes
I0817 16:01:32.051115   18497 rpc.go:439] Uploaded segment 7
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x49f56c9]

goroutine 195 [running]:
github.com/livepeer/go-livepeer/server.gotRTMPStreamHandler.func1.1.1.1(0xc4207f8290, 0xc4208aa180, 0x76b625897673d840, 0xc42057a7b0, 0xc4203495c0)
	/Users/ericxtang/Code/Livepeer/lpdev-data/go/src/github.com/livepeer/go-livepeer/server/mediaserver.go:378 +0x159
created by github.com/livepeer/go-livepeer/server.gotRTMPStreamHandler.func1.1.1
	/Users/ericxtang/Code/Livepeer/lpdev-data/go/src/github.com/livepeer/go-livepeer/server/mediaserver.go:341 +0x121
```

**To Reproduce**
1. Start a node on Rinkey `livepeer --rinkeby`
2. Configure the broadcast price and options as shown above.
3. Stream into it from OBS
4. Observe crash a few seconds later

**Expected behavior**
Node to continue to run

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS X High Sierra

**Additional context**
Also note the /Users/ericxtang displayable in the build error output - that seems weird.

**Comment by j0sh** [comment]
Interesting. @ericxtang what's the git commit that was used in this build?

The backtrace looks somewhat like an error that was fixed here https://github.com/livepeer/go-livepeer/pull/512/commits/c7933cda57104e8d9e292e5c510c36cb83671cc1 but the `ja/nodeid` branch was not rebased onto `ja/v2feedback` until earlier this afternoon, so this build might not have all the latest fixes.

**Comment by ericxtang** [comment]
This bug should be fixed.  Let's close it if we can no longer reproduce.

**Comment by ericxtang** [comment]
Fixed
