### ISSUE TITLE
Invalid memory address or nil pointer when recovering claims as transcoder

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#520]
**Describe the bug**

Upon stopping and starting one of the Rinkeby transcoder nodes, it crashes with the following error message after trying to recover claims:

```
I0820 21:48:22.190621   29673 db.go:623] Inserting claim for job 3217
I0820 21:48:22.185807   29673 claimmanager.go:122] claimmanager: Fetching claims for job 3346
I0820 21:48:22.185826   29673 claimmanager.go:140] claimmanager: Starting recovery for 3346
I0820 21:48:22.190759   29673 db.go:640] Guessed claim ID to be 13 for job 3217
I0820 21:48:22.190747   29673 claimmanager.go:307] Job 3225 Claiming for segs: [24 66 141 143 144 60 91 96 39 53 117 32 47 104 85 121 137 51 62 81 73 75 125 139 35 49 64 107 129 5
7 89 94 71 134 132 136 38 69 83 147 34 58 127 115 145 77 100 109 55 87 106 102 128 41 45 68 98 30 43 79 113 26 28 92 111 119 122] ranges: [[24 24] [26 26] [28 28] [30 30] [32 32]
[34 35] [38 39] [41 41] [43 43] [45 45] [47 47] [49 49] [51 51] [53 53] [55 55] [57 58] [60 60] [62 62] [64 64] [66 66] [68 69] [71 71] [73 73] [75 75] [77 77] [79 79] [81 81] [83
 83] [85 85] [87 87] [89 89] [91 92] [94 94] [96 96] [98 98] [100 100] [102 102] [104 104] [106 107] [109 109] [111 111] [113 113] [115 115] [117 117] [119 119] [121 122] [125 125
] [127 129] [132 132] [134 134] [136 137] [139 139] [141 141] [143 145] [147 147]]
I0820 21:48:22.190820   29673 db.go:623] Inserting claim for job 3225
I0820 21:48:22.191631   29673 db.go:640] Guessed claim ID to be 9 for job 3225
E0820 21:48:22.191658   29673 db.go:643] Unable to insert claim database is locked
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdecfa8]

goroutine 455 [running]:
github.com/livepeer/go-livepeer/eth.(*BasicClaimManager).ClaimVerifyAndDistributeFees(0xc42077ae70, 0xc4207847a0, 0x2)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/eth/claimmanager.go:339 +0x1238
github.com/livepeer/go-livepeer/eth.RecoverClaims.func1(0xc420350010, 0xc42077ae70)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/eth/claimmanager.go:141 +0xd3
created by github.com/livepeer/go-livepeer/eth.RecoverClaims
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/eth/claimmanager.go:139 +0x592
```

**To Reproduce**
1. Stop transcoder node 0x94107cB2261e722f9F4908115546Eeee17dECada on Rinkeby
2. Start transcoder node 0x94107cB2261e722f9F4908115546Eeee17dECada on Rinkeby

**Expected behavior**

Node to not crash when trying to recover claims.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.2
 - Version: `ja/nodeid`

**Comment by yondonfu** [comment]
Looks like the problematic line is here: https://github.com/livepeer/go-livepeer/blob/adc55c9882fc4fc91443dde961be449127b8f081/eth/claimmanager.go#L339

We should check the error returned by `c.db.InsertClaim()` because if it returns an error, then `claimIDp` will be nil resulting in a nil pointer exception which is the root of this issue. The error in this case is a `database is locked` error which makes sense because when the transcoder node restarts it will try to submit claims based on unclaimed receipts - the node creates a separate goroutine for each claim process which can result in one of these goroutines obtaining the database lock forcing the rest to wait.

**Comment by yondonfu** [comment]
Realized this is a duplicate of #494 so closing this - a fix for this can be tracked there.
